### ISSUE TITLE
Adding text-hyphens, rouge and pygments to Dockerfile.vulkan-docs-base

### ISSUE THREAD

**Issue by keryell** [KhronosGroup/DockerContainers#9]
According to https://gitlab.khronos.org/sycl/Specification/-/merge_requests/565#note_285846 and https://gitlab.khronos.org/sycl/Specification/-/issues/454#note_285542 I think some packages could be added.

**Comment by oddhack** [comment]
Give it a try now. I think all the relevant packages are on dockerhub.
